/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.projet2.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CrashReport extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5346125210212618195L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CrashReport\",\"namespace\":\"com.projet2.events\",\"fields\":[{\"name\":\"gameId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gameName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"platform\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"errorMessage\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"stackTrace\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CrashReport> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CrashReport> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CrashReport> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CrashReport> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CrashReport> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CrashReport to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CrashReport from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CrashReport instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CrashReport fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String gameId;
  private java.lang.String gameName;
  private java.lang.String platform;
  private java.lang.String errorMessage;
  private java.lang.String stackTrace;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CrashReport() {}

  /**
   * All-args constructor.
   * @param gameId The new value for gameId
   * @param gameName The new value for gameName
   * @param platform The new value for platform
   * @param errorMessage The new value for errorMessage
   * @param stackTrace The new value for stackTrace
   * @param timestamp The new value for timestamp
   */
  public CrashReport(java.lang.String gameId, java.lang.String gameName, java.lang.String platform, java.lang.String errorMessage, java.lang.String stackTrace, java.lang.Long timestamp) {
    this.gameId = gameId;
    this.gameName = gameName;
    this.platform = platform;
    this.errorMessage = errorMessage;
    this.stackTrace = stackTrace;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gameId;
    case 1: return gameName;
    case 2: return platform;
    case 3: return errorMessage;
    case 4: return stackTrace;
    case 5: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gameId = value$ != null ? value$.toString() : null; break;
    case 1: gameName = value$ != null ? value$.toString() : null; break;
    case 2: platform = value$ != null ? value$.toString() : null; break;
    case 3: errorMessage = value$ != null ? value$.toString() : null; break;
    case 4: stackTrace = value$ != null ? value$.toString() : null; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'gameId' field.
   * @return The value of the 'gameId' field.
   */
  public java.lang.String getGameId() {
    return gameId;
  }


  /**
   * Sets the value of the 'gameId' field.
   * @param value the value to set.
   */
  public void setGameId(java.lang.String value) {
    this.gameId = value;
  }

  /**
   * Gets the value of the 'gameName' field.
   * @return The value of the 'gameName' field.
   */
  public java.lang.String getGameName() {
    return gameName;
  }


  /**
   * Sets the value of the 'gameName' field.
   * @param value the value to set.
   */
  public void setGameName(java.lang.String value) {
    this.gameName = value;
  }

  /**
   * Gets the value of the 'platform' field.
   * @return The value of the 'platform' field.
   */
  public java.lang.String getPlatform() {
    return platform;
  }


  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.String value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'stackTrace' field.
   * @return The value of the 'stackTrace' field.
   */
  public java.lang.String getStackTrace() {
    return stackTrace;
  }


  /**
   * Sets the value of the 'stackTrace' field.
   * @param value the value to set.
   */
  public void setStackTrace(java.lang.String value) {
    this.stackTrace = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new CrashReport RecordBuilder.
   * @return A new CrashReport RecordBuilder
   */
  public static com.projet2.events.CrashReport.Builder newBuilder() {
    return new com.projet2.events.CrashReport.Builder();
  }

  /**
   * Creates a new CrashReport RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CrashReport RecordBuilder
   */
  public static com.projet2.events.CrashReport.Builder newBuilder(com.projet2.events.CrashReport.Builder other) {
    if (other == null) {
      return new com.projet2.events.CrashReport.Builder();
    } else {
      return new com.projet2.events.CrashReport.Builder(other);
    }
  }

  /**
   * Creates a new CrashReport RecordBuilder by copying an existing CrashReport instance.
   * @param other The existing instance to copy.
   * @return A new CrashReport RecordBuilder
   */
  public static com.projet2.events.CrashReport.Builder newBuilder(com.projet2.events.CrashReport other) {
    if (other == null) {
      return new com.projet2.events.CrashReport.Builder();
    } else {
      return new com.projet2.events.CrashReport.Builder(other);
    }
  }

  /**
   * RecordBuilder for CrashReport instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CrashReport>
    implements org.apache.avro.data.RecordBuilder<CrashReport> {

    private java.lang.String gameId;
    private java.lang.String gameName;
    private java.lang.String platform;
    private java.lang.String errorMessage;
    private java.lang.String stackTrace;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.projet2.events.CrashReport.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gameId)) {
        this.gameId = data().deepCopy(fields()[0].schema(), other.gameId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.gameName)) {
        this.gameName = data().deepCopy(fields()[1].schema(), other.gameName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[3].schema(), other.errorMessage);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.stackTrace)) {
        this.stackTrace = data().deepCopy(fields()[4].schema(), other.stackTrace);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing CrashReport instance
     * @param other The existing instance to copy.
     */
    private Builder(com.projet2.events.CrashReport other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.gameId)) {
        this.gameId = data().deepCopy(fields()[0].schema(), other.gameId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gameName)) {
        this.gameName = data().deepCopy(fields()[1].schema(), other.gameName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[3].schema(), other.errorMessage);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.stackTrace)) {
        this.stackTrace = data().deepCopy(fields()[4].schema(), other.stackTrace);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'gameId' field.
      * @return The value.
      */
    public java.lang.String getGameId() {
      return gameId;
    }


    /**
      * Sets the value of the 'gameId' field.
      * @param value The value of 'gameId'.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder setGameId(java.lang.String value) {
      validate(fields()[0], value);
      this.gameId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gameId' field has been set.
      * @return True if the 'gameId' field has been set, false otherwise.
      */
    public boolean hasGameId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gameId' field.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder clearGameId() {
      gameId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gameName' field.
      * @return The value.
      */
    public java.lang.String getGameName() {
      return gameName;
    }


    /**
      * Sets the value of the 'gameName' field.
      * @param value The value of 'gameName'.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder setGameName(java.lang.String value) {
      validate(fields()[1], value);
      this.gameName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gameName' field has been set.
      * @return True if the 'gameName' field has been set, false otherwise.
      */
    public boolean hasGameName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'gameName' field.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder clearGameName() {
      gameName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform' field.
      * @return The value.
      */
    public java.lang.String getPlatform() {
      return platform;
    }


    /**
      * Sets the value of the 'platform' field.
      * @param value The value of 'platform'.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder setPlatform(java.lang.String value) {
      validate(fields()[2], value);
      this.platform = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'platform' field has been set.
      * @return True if the 'platform' field has been set, false otherwise.
      */
    public boolean hasPlatform() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'platform' field.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[3], value);
      this.errorMessage = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'stackTrace' field.
      * @return The value.
      */
    public java.lang.String getStackTrace() {
      return stackTrace;
    }


    /**
      * Sets the value of the 'stackTrace' field.
      * @param value The value of 'stackTrace'.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder setStackTrace(java.lang.String value) {
      validate(fields()[4], value);
      this.stackTrace = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'stackTrace' field has been set.
      * @return True if the 'stackTrace' field has been set, false otherwise.
      */
    public boolean hasStackTrace() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'stackTrace' field.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder clearStackTrace() {
      stackTrace = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder setTimestamp(long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.projet2.events.CrashReport.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CrashReport build() {
      try {
        CrashReport record = new CrashReport();
        record.gameId = fieldSetFlags()[0] ? this.gameId : (java.lang.String) defaultValue(fields()[0]);
        record.gameName = fieldSetFlags()[1] ? this.gameName : (java.lang.String) defaultValue(fields()[1]);
        record.platform = fieldSetFlags()[2] ? this.platform : (java.lang.String) defaultValue(fields()[2]);
        record.errorMessage = fieldSetFlags()[3] ? this.errorMessage : (java.lang.String) defaultValue(fields()[3]);
        record.stackTrace = fieldSetFlags()[4] ? this.stackTrace : (java.lang.String) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CrashReport>
    WRITER$ = (org.apache.avro.io.DatumWriter<CrashReport>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CrashReport>
    READER$ = (org.apache.avro.io.DatumReader<CrashReport>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.gameId);

    out.writeString(this.gameName);

    out.writeString(this.platform);

    out.writeString(this.errorMessage);

    out.writeString(this.stackTrace);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.gameId = in.readString();

      this.gameName = in.readString();

      this.platform = in.readString();

      this.errorMessage = in.readString();

      this.stackTrace = in.readString();

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.gameId = in.readString();
          break;

        case 1:
          this.gameName = in.readString();
          break;

        case 2:
          this.platform = in.readString();
          break;

        case 3:
          this.errorMessage = in.readString();
          break;

        case 4:
          this.stackTrace = in.readString();
          break;

        case 5:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










