/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.projet2.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GamePublished extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4534258063632513332L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GamePublished\",\"namespace\":\"com.projet2.events\",\"fields\":[{\"name\":\"gameId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gameName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"platform\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"genre\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"version\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"publisherName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"publishedAt\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GamePublished> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GamePublished> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GamePublished> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GamePublished> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GamePublished> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GamePublished to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GamePublished from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GamePublished instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GamePublished fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String gameId;
  private java.lang.String gameName;
  private java.lang.String platform;
  private java.util.List<java.lang.String> genre;
  private java.lang.String version;
  private java.lang.String publisherName;
  private long publishedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GamePublished() {}

  /**
   * All-args constructor.
   * @param gameId The new value for gameId
   * @param gameName The new value for gameName
   * @param platform The new value for platform
   * @param genre The new value for genre
   * @param version The new value for version
   * @param publisherName The new value for publisherName
   * @param publishedAt The new value for publishedAt
   */
  public GamePublished(java.lang.String gameId, java.lang.String gameName, java.lang.String platform, java.util.List<java.lang.String> genre, java.lang.String version, java.lang.String publisherName, java.lang.Long publishedAt) {
    this.gameId = gameId;
    this.gameName = gameName;
    this.platform = platform;
    this.genre = genre;
    this.version = version;
    this.publisherName = publisherName;
    this.publishedAt = publishedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gameId;
    case 1: return gameName;
    case 2: return platform;
    case 3: return genre;
    case 4: return version;
    case 5: return publisherName;
    case 6: return publishedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gameId = value$ != null ? value$.toString() : null; break;
    case 1: gameName = value$ != null ? value$.toString() : null; break;
    case 2: platform = value$ != null ? value$.toString() : null; break;
    case 3: genre = (java.util.List<java.lang.String>)value$; break;
    case 4: version = value$ != null ? value$.toString() : null; break;
    case 5: publisherName = value$ != null ? value$.toString() : null; break;
    case 6: publishedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'gameId' field.
   * @return The value of the 'gameId' field.
   */
  public java.lang.String getGameId() {
    return gameId;
  }


  /**
   * Sets the value of the 'gameId' field.
   * @param value the value to set.
   */
  public void setGameId(java.lang.String value) {
    this.gameId = value;
  }

  /**
   * Gets the value of the 'gameName' field.
   * @return The value of the 'gameName' field.
   */
  public java.lang.String getGameName() {
    return gameName;
  }


  /**
   * Sets the value of the 'gameName' field.
   * @param value the value to set.
   */
  public void setGameName(java.lang.String value) {
    this.gameName = value;
  }

  /**
   * Gets the value of the 'platform' field.
   * @return The value of the 'platform' field.
   */
  public java.lang.String getPlatform() {
    return platform;
  }


  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.String value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'genre' field.
   * @return The value of the 'genre' field.
   */
  public java.util.List<java.lang.String> getGenre() {
    return genre;
  }


  /**
   * Sets the value of the 'genre' field.
   * @param value the value to set.
   */
  public void setGenre(java.util.List<java.lang.String> value) {
    this.genre = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public java.lang.String getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.String value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'publisherName' field.
   * @return The value of the 'publisherName' field.
   */
  public java.lang.String getPublisherName() {
    return publisherName;
  }


  /**
   * Sets the value of the 'publisherName' field.
   * @param value the value to set.
   */
  public void setPublisherName(java.lang.String value) {
    this.publisherName = value;
  }

  /**
   * Gets the value of the 'publishedAt' field.
   * @return The value of the 'publishedAt' field.
   */
  public long getPublishedAt() {
    return publishedAt;
  }


  /**
   * Sets the value of the 'publishedAt' field.
   * @param value the value to set.
   */
  public void setPublishedAt(long value) {
    this.publishedAt = value;
  }

  /**
   * Creates a new GamePublished RecordBuilder.
   * @return A new GamePublished RecordBuilder
   */
  public static com.projet2.events.GamePublished.Builder newBuilder() {
    return new com.projet2.events.GamePublished.Builder();
  }

  /**
   * Creates a new GamePublished RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GamePublished RecordBuilder
   */
  public static com.projet2.events.GamePublished.Builder newBuilder(com.projet2.events.GamePublished.Builder other) {
    if (other == null) {
      return new com.projet2.events.GamePublished.Builder();
    } else {
      return new com.projet2.events.GamePublished.Builder(other);
    }
  }

  /**
   * Creates a new GamePublished RecordBuilder by copying an existing GamePublished instance.
   * @param other The existing instance to copy.
   * @return A new GamePublished RecordBuilder
   */
  public static com.projet2.events.GamePublished.Builder newBuilder(com.projet2.events.GamePublished other) {
    if (other == null) {
      return new com.projet2.events.GamePublished.Builder();
    } else {
      return new com.projet2.events.GamePublished.Builder(other);
    }
  }

  /**
   * RecordBuilder for GamePublished instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GamePublished>
    implements org.apache.avro.data.RecordBuilder<GamePublished> {

    private java.lang.String gameId;
    private java.lang.String gameName;
    private java.lang.String platform;
    private java.util.List<java.lang.String> genre;
    private java.lang.String version;
    private java.lang.String publisherName;
    private long publishedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.projet2.events.GamePublished.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gameId)) {
        this.gameId = data().deepCopy(fields()[0].schema(), other.gameId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.gameName)) {
        this.gameName = data().deepCopy(fields()[1].schema(), other.gameName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.genre)) {
        this.genre = data().deepCopy(fields()[3].schema(), other.genre);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.version)) {
        this.version = data().deepCopy(fields()[4].schema(), other.version);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.publisherName)) {
        this.publisherName = data().deepCopy(fields()[5].schema(), other.publisherName);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[6].schema(), other.publishedAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing GamePublished instance
     * @param other The existing instance to copy.
     */
    private Builder(com.projet2.events.GamePublished other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.gameId)) {
        this.gameId = data().deepCopy(fields()[0].schema(), other.gameId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gameName)) {
        this.gameName = data().deepCopy(fields()[1].schema(), other.gameName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.genre)) {
        this.genre = data().deepCopy(fields()[3].schema(), other.genre);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.version)) {
        this.version = data().deepCopy(fields()[4].schema(), other.version);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.publisherName)) {
        this.publisherName = data().deepCopy(fields()[5].schema(), other.publisherName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[6].schema(), other.publishedAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'gameId' field.
      * @return The value.
      */
    public java.lang.String getGameId() {
      return gameId;
    }


    /**
      * Sets the value of the 'gameId' field.
      * @param value The value of 'gameId'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setGameId(java.lang.String value) {
      validate(fields()[0], value);
      this.gameId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gameId' field has been set.
      * @return True if the 'gameId' field has been set, false otherwise.
      */
    public boolean hasGameId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gameId' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearGameId() {
      gameId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gameName' field.
      * @return The value.
      */
    public java.lang.String getGameName() {
      return gameName;
    }


    /**
      * Sets the value of the 'gameName' field.
      * @param value The value of 'gameName'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setGameName(java.lang.String value) {
      validate(fields()[1], value);
      this.gameName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gameName' field has been set.
      * @return True if the 'gameName' field has been set, false otherwise.
      */
    public boolean hasGameName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'gameName' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearGameName() {
      gameName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform' field.
      * @return The value.
      */
    public java.lang.String getPlatform() {
      return platform;
    }


    /**
      * Sets the value of the 'platform' field.
      * @param value The value of 'platform'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setPlatform(java.lang.String value) {
      validate(fields()[2], value);
      this.platform = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'platform' field has been set.
      * @return True if the 'platform' field has been set, false otherwise.
      */
    public boolean hasPlatform() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'platform' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'genre' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getGenre() {
      return genre;
    }


    /**
      * Sets the value of the 'genre' field.
      * @param value The value of 'genre'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setGenre(java.util.List<java.lang.String> value) {
      validate(fields()[3], value);
      this.genre = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'genre' field has been set.
      * @return True if the 'genre' field has been set, false otherwise.
      */
    public boolean hasGenre() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'genre' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearGenre() {
      genre = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public java.lang.String getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setVersion(java.lang.String value) {
      validate(fields()[4], value);
      this.version = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearVersion() {
      version = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisherName' field.
      * @return The value.
      */
    public java.lang.String getPublisherName() {
      return publisherName;
    }


    /**
      * Sets the value of the 'publisherName' field.
      * @param value The value of 'publisherName'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setPublisherName(java.lang.String value) {
      validate(fields()[5], value);
      this.publisherName = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'publisherName' field has been set.
      * @return True if the 'publisherName' field has been set, false otherwise.
      */
    public boolean hasPublisherName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'publisherName' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearPublisherName() {
      publisherName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedAt' field.
      * @return The value.
      */
    public long getPublishedAt() {
      return publishedAt;
    }


    /**
      * Sets the value of the 'publishedAt' field.
      * @param value The value of 'publishedAt'.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder setPublishedAt(long value) {
      validate(fields()[6], value);
      this.publishedAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedAt' field has been set.
      * @return True if the 'publishedAt' field has been set, false otherwise.
      */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'publishedAt' field.
      * @return This builder.
      */
    public com.projet2.events.GamePublished.Builder clearPublishedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GamePublished build() {
      try {
        GamePublished record = new GamePublished();
        record.gameId = fieldSetFlags()[0] ? this.gameId : (java.lang.String) defaultValue(fields()[0]);
        record.gameName = fieldSetFlags()[1] ? this.gameName : (java.lang.String) defaultValue(fields()[1]);
        record.platform = fieldSetFlags()[2] ? this.platform : (java.lang.String) defaultValue(fields()[2]);
        record.genre = fieldSetFlags()[3] ? this.genre : (java.util.List<java.lang.String>) defaultValue(fields()[3]);
        record.version = fieldSetFlags()[4] ? this.version : (java.lang.String) defaultValue(fields()[4]);
        record.publisherName = fieldSetFlags()[5] ? this.publisherName : (java.lang.String) defaultValue(fields()[5]);
        record.publishedAt = fieldSetFlags()[6] ? this.publishedAt : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GamePublished>
    WRITER$ = (org.apache.avro.io.DatumWriter<GamePublished>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GamePublished>
    READER$ = (org.apache.avro.io.DatumReader<GamePublished>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.gameId);

    out.writeString(this.gameName);

    out.writeString(this.platform);

    long size0 = this.genre.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.genre) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.version);

    out.writeString(this.publisherName);

    out.writeLong(this.publishedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.gameId = in.readString();

      this.gameName = in.readString();

      this.platform = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.genre;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("genre").schema());
        this.genre = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

      this.version = in.readString();

      this.publisherName = in.readString();

      this.publishedAt = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.gameId = in.readString();
          break;

        case 1:
          this.gameName = in.readString();
          break;

        case 2:
          this.platform = in.readString();
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.genre;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("genre").schema());
            this.genre = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        case 4:
          this.version = in.readString();
          break;

        case 5:
          this.publisherName = in.readString();
          break;

        case 6:
          this.publishedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










