/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.projet2.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GamePurchased extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8271679651455424319L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GamePurchased\",\"namespace\":\"com.projet2.events\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gameId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gameName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"purchasedAt\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GamePurchased> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GamePurchased> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GamePurchased> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GamePurchased> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GamePurchased> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GamePurchased to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GamePurchased from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GamePurchased instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GamePurchased fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String userId;
  private java.lang.String gameId;
  private java.lang.String gameName;
  private long purchasedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GamePurchased() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param gameId The new value for gameId
   * @param gameName The new value for gameName
   * @param purchasedAt The new value for purchasedAt
   */
  public GamePurchased(java.lang.String userId, java.lang.String gameId, java.lang.String gameName, java.lang.Long purchasedAt) {
    this.userId = userId;
    this.gameId = gameId;
    this.gameName = gameName;
    this.purchasedAt = purchasedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return gameId;
    case 2: return gameName;
    case 3: return purchasedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = value$ != null ? value$.toString() : null; break;
    case 1: gameId = value$ != null ? value$.toString() : null; break;
    case 2: gameName = value$ != null ? value$.toString() : null; break;
    case 3: purchasedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'gameId' field.
   * @return The value of the 'gameId' field.
   */
  public java.lang.String getGameId() {
    return gameId;
  }


  /**
   * Sets the value of the 'gameId' field.
   * @param value the value to set.
   */
  public void setGameId(java.lang.String value) {
    this.gameId = value;
  }

  /**
   * Gets the value of the 'gameName' field.
   * @return The value of the 'gameName' field.
   */
  public java.lang.String getGameName() {
    return gameName;
  }


  /**
   * Sets the value of the 'gameName' field.
   * @param value the value to set.
   */
  public void setGameName(java.lang.String value) {
    this.gameName = value;
  }

  /**
   * Gets the value of the 'purchasedAt' field.
   * @return The value of the 'purchasedAt' field.
   */
  public long getPurchasedAt() {
    return purchasedAt;
  }


  /**
   * Sets the value of the 'purchasedAt' field.
   * @param value the value to set.
   */
  public void setPurchasedAt(long value) {
    this.purchasedAt = value;
  }

  /**
   * Creates a new GamePurchased RecordBuilder.
   * @return A new GamePurchased RecordBuilder
   */
  public static com.projet2.events.GamePurchased.Builder newBuilder() {
    return new com.projet2.events.GamePurchased.Builder();
  }

  /**
   * Creates a new GamePurchased RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GamePurchased RecordBuilder
   */
  public static com.projet2.events.GamePurchased.Builder newBuilder(com.projet2.events.GamePurchased.Builder other) {
    if (other == null) {
      return new com.projet2.events.GamePurchased.Builder();
    } else {
      return new com.projet2.events.GamePurchased.Builder(other);
    }
  }

  /**
   * Creates a new GamePurchased RecordBuilder by copying an existing GamePurchased instance.
   * @param other The existing instance to copy.
   * @return A new GamePurchased RecordBuilder
   */
  public static com.projet2.events.GamePurchased.Builder newBuilder(com.projet2.events.GamePurchased other) {
    if (other == null) {
      return new com.projet2.events.GamePurchased.Builder();
    } else {
      return new com.projet2.events.GamePurchased.Builder(other);
    }
  }

  /**
   * RecordBuilder for GamePurchased instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GamePurchased>
    implements org.apache.avro.data.RecordBuilder<GamePurchased> {

    private java.lang.String userId;
    private java.lang.String gameId;
    private java.lang.String gameName;
    private long purchasedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.projet2.events.GamePurchased.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.gameId)) {
        this.gameId = data().deepCopy(fields()[1].schema(), other.gameId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.gameName)) {
        this.gameName = data().deepCopy(fields()[2].schema(), other.gameName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.purchasedAt)) {
        this.purchasedAt = data().deepCopy(fields()[3].schema(), other.purchasedAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing GamePurchased instance
     * @param other The existing instance to copy.
     */
    private Builder(com.projet2.events.GamePurchased other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gameId)) {
        this.gameId = data().deepCopy(fields()[1].schema(), other.gameId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.gameName)) {
        this.gameName = data().deepCopy(fields()[2].schema(), other.gameName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.purchasedAt)) {
        this.purchasedAt = data().deepCopy(fields()[3].schema(), other.purchasedAt);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gameId' field.
      * @return The value.
      */
    public java.lang.String getGameId() {
      return gameId;
    }


    /**
      * Sets the value of the 'gameId' field.
      * @param value The value of 'gameId'.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder setGameId(java.lang.String value) {
      validate(fields()[1], value);
      this.gameId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gameId' field has been set.
      * @return True if the 'gameId' field has been set, false otherwise.
      */
    public boolean hasGameId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'gameId' field.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder clearGameId() {
      gameId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'gameName' field.
      * @return The value.
      */
    public java.lang.String getGameName() {
      return gameName;
    }


    /**
      * Sets the value of the 'gameName' field.
      * @param value The value of 'gameName'.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder setGameName(java.lang.String value) {
      validate(fields()[2], value);
      this.gameName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'gameName' field has been set.
      * @return True if the 'gameName' field has been set, false otherwise.
      */
    public boolean hasGameName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'gameName' field.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder clearGameName() {
      gameName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'purchasedAt' field.
      * @return The value.
      */
    public long getPurchasedAt() {
      return purchasedAt;
    }


    /**
      * Sets the value of the 'purchasedAt' field.
      * @param value The value of 'purchasedAt'.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder setPurchasedAt(long value) {
      validate(fields()[3], value);
      this.purchasedAt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'purchasedAt' field has been set.
      * @return True if the 'purchasedAt' field has been set, false otherwise.
      */
    public boolean hasPurchasedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'purchasedAt' field.
      * @return This builder.
      */
    public com.projet2.events.GamePurchased.Builder clearPurchasedAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GamePurchased build() {
      try {
        GamePurchased record = new GamePurchased();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.gameId = fieldSetFlags()[1] ? this.gameId : (java.lang.String) defaultValue(fields()[1]);
        record.gameName = fieldSetFlags()[2] ? this.gameName : (java.lang.String) defaultValue(fields()[2]);
        record.purchasedAt = fieldSetFlags()[3] ? this.purchasedAt : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GamePurchased>
    WRITER$ = (org.apache.avro.io.DatumWriter<GamePurchased>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GamePurchased>
    READER$ = (org.apache.avro.io.DatumReader<GamePurchased>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.gameId);

    out.writeString(this.gameName);

    out.writeLong(this.purchasedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString();

      this.gameId = in.readString();

      this.gameName = in.readString();

      this.purchasedAt = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString();
          break;

        case 1:
          this.gameId = in.readString();
          break;

        case 2:
          this.gameName = in.readString();
          break;

        case 3:
          this.purchasedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










