/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.projet2.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PatchReleased extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2382986389246315143L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PatchReleased\",\"namespace\":\"com.projet2.events\",\"fields\":[{\"name\":\"gameId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gameName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"platform\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"newVersion\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"editorComment\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"changes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"PatchChange\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}},{\"name\":\"releasedAt\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PatchReleased> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PatchReleased> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PatchReleased> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PatchReleased> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PatchReleased> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PatchReleased to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PatchReleased from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PatchReleased instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PatchReleased fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String gameId;
  private java.lang.String gameName;
  private java.lang.String platform;
  private java.lang.String newVersion;
  private java.lang.String editorComment;
  private java.util.List<com.projet2.events.PatchChange> changes;
  private long releasedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PatchReleased() {}

  /**
   * All-args constructor.
   * @param gameId The new value for gameId
   * @param gameName The new value for gameName
   * @param platform The new value for platform
   * @param newVersion The new value for newVersion
   * @param editorComment The new value for editorComment
   * @param changes The new value for changes
   * @param releasedAt The new value for releasedAt
   */
  public PatchReleased(java.lang.String gameId, java.lang.String gameName, java.lang.String platform, java.lang.String newVersion, java.lang.String editorComment, java.util.List<com.projet2.events.PatchChange> changes, java.lang.Long releasedAt) {
    this.gameId = gameId;
    this.gameName = gameName;
    this.platform = platform;
    this.newVersion = newVersion;
    this.editorComment = editorComment;
    this.changes = changes;
    this.releasedAt = releasedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gameId;
    case 1: return gameName;
    case 2: return platform;
    case 3: return newVersion;
    case 4: return editorComment;
    case 5: return changes;
    case 6: return releasedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gameId = value$ != null ? value$.toString() : null; break;
    case 1: gameName = value$ != null ? value$.toString() : null; break;
    case 2: platform = value$ != null ? value$.toString() : null; break;
    case 3: newVersion = value$ != null ? value$.toString() : null; break;
    case 4: editorComment = value$ != null ? value$.toString() : null; break;
    case 5: changes = (java.util.List<com.projet2.events.PatchChange>)value$; break;
    case 6: releasedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'gameId' field.
   * @return The value of the 'gameId' field.
   */
  public java.lang.String getGameId() {
    return gameId;
  }


  /**
   * Sets the value of the 'gameId' field.
   * @param value the value to set.
   */
  public void setGameId(java.lang.String value) {
    this.gameId = value;
  }

  /**
   * Gets the value of the 'gameName' field.
   * @return The value of the 'gameName' field.
   */
  public java.lang.String getGameName() {
    return gameName;
  }


  /**
   * Sets the value of the 'gameName' field.
   * @param value the value to set.
   */
  public void setGameName(java.lang.String value) {
    this.gameName = value;
  }

  /**
   * Gets the value of the 'platform' field.
   * @return The value of the 'platform' field.
   */
  public java.lang.String getPlatform() {
    return platform;
  }


  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.String value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'newVersion' field.
   * @return The value of the 'newVersion' field.
   */
  public java.lang.String getNewVersion() {
    return newVersion;
  }


  /**
   * Sets the value of the 'newVersion' field.
   * @param value the value to set.
   */
  public void setNewVersion(java.lang.String value) {
    this.newVersion = value;
  }

  /**
   * Gets the value of the 'editorComment' field.
   * @return The value of the 'editorComment' field.
   */
  public java.lang.String getEditorComment() {
    return editorComment;
  }


  /**
   * Sets the value of the 'editorComment' field.
   * @param value the value to set.
   */
  public void setEditorComment(java.lang.String value) {
    this.editorComment = value;
  }

  /**
   * Gets the value of the 'changes' field.
   * @return The value of the 'changes' field.
   */
  public java.util.List<com.projet2.events.PatchChange> getChanges() {
    return changes;
  }


  /**
   * Sets the value of the 'changes' field.
   * @param value the value to set.
   */
  public void setChanges(java.util.List<com.projet2.events.PatchChange> value) {
    this.changes = value;
  }

  /**
   * Gets the value of the 'releasedAt' field.
   * @return The value of the 'releasedAt' field.
   */
  public long getReleasedAt() {
    return releasedAt;
  }


  /**
   * Sets the value of the 'releasedAt' field.
   * @param value the value to set.
   */
  public void setReleasedAt(long value) {
    this.releasedAt = value;
  }

  /**
   * Creates a new PatchReleased RecordBuilder.
   * @return A new PatchReleased RecordBuilder
   */
  public static com.projet2.events.PatchReleased.Builder newBuilder() {
    return new com.projet2.events.PatchReleased.Builder();
  }

  /**
   * Creates a new PatchReleased RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PatchReleased RecordBuilder
   */
  public static com.projet2.events.PatchReleased.Builder newBuilder(com.projet2.events.PatchReleased.Builder other) {
    if (other == null) {
      return new com.projet2.events.PatchReleased.Builder();
    } else {
      return new com.projet2.events.PatchReleased.Builder(other);
    }
  }

  /**
   * Creates a new PatchReleased RecordBuilder by copying an existing PatchReleased instance.
   * @param other The existing instance to copy.
   * @return A new PatchReleased RecordBuilder
   */
  public static com.projet2.events.PatchReleased.Builder newBuilder(com.projet2.events.PatchReleased other) {
    if (other == null) {
      return new com.projet2.events.PatchReleased.Builder();
    } else {
      return new com.projet2.events.PatchReleased.Builder(other);
    }
  }

  /**
   * RecordBuilder for PatchReleased instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PatchReleased>
    implements org.apache.avro.data.RecordBuilder<PatchReleased> {

    private java.lang.String gameId;
    private java.lang.String gameName;
    private java.lang.String platform;
    private java.lang.String newVersion;
    private java.lang.String editorComment;
    private java.util.List<com.projet2.events.PatchChange> changes;
    private long releasedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.projet2.events.PatchReleased.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gameId)) {
        this.gameId = data().deepCopy(fields()[0].schema(), other.gameId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.gameName)) {
        this.gameName = data().deepCopy(fields()[1].schema(), other.gameName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.newVersion)) {
        this.newVersion = data().deepCopy(fields()[3].schema(), other.newVersion);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.editorComment)) {
        this.editorComment = data().deepCopy(fields()[4].schema(), other.editorComment);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.changes)) {
        this.changes = data().deepCopy(fields()[5].schema(), other.changes);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.releasedAt)) {
        this.releasedAt = data().deepCopy(fields()[6].schema(), other.releasedAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing PatchReleased instance
     * @param other The existing instance to copy.
     */
    private Builder(com.projet2.events.PatchReleased other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.gameId)) {
        this.gameId = data().deepCopy(fields()[0].schema(), other.gameId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gameName)) {
        this.gameName = data().deepCopy(fields()[1].schema(), other.gameName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.newVersion)) {
        this.newVersion = data().deepCopy(fields()[3].schema(), other.newVersion);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.editorComment)) {
        this.editorComment = data().deepCopy(fields()[4].schema(), other.editorComment);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.changes)) {
        this.changes = data().deepCopy(fields()[5].schema(), other.changes);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.releasedAt)) {
        this.releasedAt = data().deepCopy(fields()[6].schema(), other.releasedAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'gameId' field.
      * @return The value.
      */
    public java.lang.String getGameId() {
      return gameId;
    }


    /**
      * Sets the value of the 'gameId' field.
      * @param value The value of 'gameId'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setGameId(java.lang.String value) {
      validate(fields()[0], value);
      this.gameId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gameId' field has been set.
      * @return True if the 'gameId' field has been set, false otherwise.
      */
    public boolean hasGameId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gameId' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearGameId() {
      gameId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gameName' field.
      * @return The value.
      */
    public java.lang.String getGameName() {
      return gameName;
    }


    /**
      * Sets the value of the 'gameName' field.
      * @param value The value of 'gameName'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setGameName(java.lang.String value) {
      validate(fields()[1], value);
      this.gameName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gameName' field has been set.
      * @return True if the 'gameName' field has been set, false otherwise.
      */
    public boolean hasGameName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'gameName' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearGameName() {
      gameName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform' field.
      * @return The value.
      */
    public java.lang.String getPlatform() {
      return platform;
    }


    /**
      * Sets the value of the 'platform' field.
      * @param value The value of 'platform'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setPlatform(java.lang.String value) {
      validate(fields()[2], value);
      this.platform = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'platform' field has been set.
      * @return True if the 'platform' field has been set, false otherwise.
      */
    public boolean hasPlatform() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'platform' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'newVersion' field.
      * @return The value.
      */
    public java.lang.String getNewVersion() {
      return newVersion;
    }


    /**
      * Sets the value of the 'newVersion' field.
      * @param value The value of 'newVersion'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setNewVersion(java.lang.String value) {
      validate(fields()[3], value);
      this.newVersion = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'newVersion' field has been set.
      * @return True if the 'newVersion' field has been set, false otherwise.
      */
    public boolean hasNewVersion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'newVersion' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearNewVersion() {
      newVersion = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'editorComment' field.
      * @return The value.
      */
    public java.lang.String getEditorComment() {
      return editorComment;
    }


    /**
      * Sets the value of the 'editorComment' field.
      * @param value The value of 'editorComment'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setEditorComment(java.lang.String value) {
      validate(fields()[4], value);
      this.editorComment = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'editorComment' field has been set.
      * @return True if the 'editorComment' field has been set, false otherwise.
      */
    public boolean hasEditorComment() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'editorComment' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearEditorComment() {
      editorComment = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'changes' field.
      * @return The value.
      */
    public java.util.List<com.projet2.events.PatchChange> getChanges() {
      return changes;
    }


    /**
      * Sets the value of the 'changes' field.
      * @param value The value of 'changes'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setChanges(java.util.List<com.projet2.events.PatchChange> value) {
      validate(fields()[5], value);
      this.changes = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'changes' field has been set.
      * @return True if the 'changes' field has been set, false otherwise.
      */
    public boolean hasChanges() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'changes' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearChanges() {
      changes = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'releasedAt' field.
      * @return The value.
      */
    public long getReleasedAt() {
      return releasedAt;
    }


    /**
      * Sets the value of the 'releasedAt' field.
      * @param value The value of 'releasedAt'.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder setReleasedAt(long value) {
      validate(fields()[6], value);
      this.releasedAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'releasedAt' field has been set.
      * @return True if the 'releasedAt' field has been set, false otherwise.
      */
    public boolean hasReleasedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'releasedAt' field.
      * @return This builder.
      */
    public com.projet2.events.PatchReleased.Builder clearReleasedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PatchReleased build() {
      try {
        PatchReleased record = new PatchReleased();
        record.gameId = fieldSetFlags()[0] ? this.gameId : (java.lang.String) defaultValue(fields()[0]);
        record.gameName = fieldSetFlags()[1] ? this.gameName : (java.lang.String) defaultValue(fields()[1]);
        record.platform = fieldSetFlags()[2] ? this.platform : (java.lang.String) defaultValue(fields()[2]);
        record.newVersion = fieldSetFlags()[3] ? this.newVersion : (java.lang.String) defaultValue(fields()[3]);
        record.editorComment = fieldSetFlags()[4] ? this.editorComment : (java.lang.String) defaultValue(fields()[4]);
        record.changes = fieldSetFlags()[5] ? this.changes : (java.util.List<com.projet2.events.PatchChange>) defaultValue(fields()[5]);
        record.releasedAt = fieldSetFlags()[6] ? this.releasedAt : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PatchReleased>
    WRITER$ = (org.apache.avro.io.DatumWriter<PatchReleased>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PatchReleased>
    READER$ = (org.apache.avro.io.DatumReader<PatchReleased>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.gameId);

    out.writeString(this.gameName);

    out.writeString(this.platform);

    out.writeString(this.newVersion);

    out.writeString(this.editorComment);

    long size0 = this.changes.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.projet2.events.PatchChange e0: this.changes) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeLong(this.releasedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.gameId = in.readString();

      this.gameName = in.readString();

      this.platform = in.readString();

      this.newVersion = in.readString();

      this.editorComment = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<com.projet2.events.PatchChange> a0 = this.changes;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.projet2.events.PatchChange>((int)size0, SCHEMA$.getField("changes").schema());
        this.changes = a0;
      } else a0.clear();
      SpecificData.Array<com.projet2.events.PatchChange> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.projet2.events.PatchChange>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.projet2.events.PatchChange e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.projet2.events.PatchChange();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.releasedAt = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.gameId = in.readString();
          break;

        case 1:
          this.gameName = in.readString();
          break;

        case 2:
          this.platform = in.readString();
          break;

        case 3:
          this.newVersion = in.readString();
          break;

        case 4:
          this.editorComment = in.readString();
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<com.projet2.events.PatchChange> a0 = this.changes;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.projet2.events.PatchChange>((int)size0, SCHEMA$.getField("changes").schema());
            this.changes = a0;
          } else a0.clear();
          SpecificData.Array<com.projet2.events.PatchChange> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.projet2.events.PatchChange>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.projet2.events.PatchChange e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.projet2.events.PatchChange();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 6:
          this.releasedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










